#!/bin/bash

# This shell script runs all of the WORKING tests that PASS.
# It will also remove all of the temporary files that are generated by the test
# cases.
# If any of the tests in this script FAIL, DO NOT PUSH YOUR CHANGES TO THE
# GITHUB REPOSITORY!

set -euo pipefail

show_usage() {
    echo "Usage: $0 [option]"
    echo
    echo "Options:"
    echo "  -a, --all     Run all tests"
    echo "  -c, --cpp     Run only the C++ API tests"
    echo "  -p, --python  Run only the Python API tests"
    echo "  -h, --help    Show this help message"
    echo
    echo "With no option, all tests are run."
}

BUILD_DIR="build"

if [ "$#" -eq 0 ]; then
    ctest --test-dir "${BUILD_DIR}" --output-on-failure
    exit 0
fi

if [ "$#" -gt 1 ]; then
    echo "Error: Expected at most one option."
    echo
    show_usage
    exit 1
fi

case "$1" in
    -a|--all)
        ctest --test-dir "${BUILD_DIR}" --output-on-failure
        ;;
    -c|--cpp)
        ctest --test-dir "${BUILD_DIR}" -L cpp_api --output-on-failure
        ;;
    -p|--python)
        ctest --test-dir "${BUILD_DIR}" -L python_api --output-on-failure
        ;;
    -h|--help)
        show_usage
        ;;
    *)
        echo "Error: Unknown option '$1'."
        echo
        show_usage
        exit 1
        ;;
esac
